# Generated by Django 5.2.4 on 2025-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_departure', models.CharField(max_length=100)),
                ('flight_destination', models.CharField(max_length=100)),
                ('flight_departure_time', models.CharField(max_length=100)),
                ('flight_destination_time', models.CharField(max_length=100)),
                ('flight_ticket_price', models.CharField(max_length=100)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.CharField(max_length=100)),
                ('passenger_gender', models.CharField(max_length=100)),
                ('passenger_phone', models.CharField(max_length=100)),
                ('passenger_email', models.CharField(max_length=100)),
                ('passenger_aadhar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='flight_companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='flight_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company_name', models.CharField(max_length=100)),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_departure', models.CharField(max_length=100)),
                ('flight_destination', models.CharField(max_length=100)),
                ('flight_departure_time', models.CharField(max_length=100)),
                ('flight_destination_time', models.CharField(max_length=100)),
                ('flight_ticket_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='historyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_departure', models.CharField(max_length=100)),
                ('flight_destination', models.CharField(max_length=100)),
                ('flight_departure_time', models.CharField(max_length=100)),
                ('flight_destination_time', models.CharField(max_length=100)),
                ('flight_ticket_price', models.CharField(max_length=100)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.CharField(max_length=100)),
                ('passenger_gender', models.CharField(max_length=100)),
                ('passenger_phone', models.CharField(max_length=100)),
                ('passenger_email', models.CharField(max_length=100)),
                ('passenger_aadhar', models.CharField(max_length=100)),
            ],
        ),
    ]
