# Generated by Django 5.2.4 on 2025-07-24 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='flight_companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='flight_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company_name', models.CharField(max_length=100)),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_departure', models.CharField(max_length=100)),
                ('flight_destination', models.CharField(max_length=100)),
                ('flight_departure_time', models.CharField(max_length=100)),
                ('flight_destination_time', models.CharField(max_length=100)),
                ('flight_ticket_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='bookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_departure', models.CharField(max_length=100)),
                ('flight_destination', models.CharField(max_length=100)),
                ('flight_departure_time', models.CharField(max_length=100)),
                ('flight_destination_time', models.CharField(max_length=100)),
                ('flight_ticket_price', models.CharField(max_length=100)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.CharField(max_length=100)),
                ('passenger_gender', models.CharField(max_length=100)),
                ('passenger_phone', models.CharField(max_length=100)),
                ('passenger_email', models.CharField(max_length=100)),
                ('passenger_aadhar', models.CharField(max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='historyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_departure', models.CharField(max_length=100)),
                ('flight_destination', models.CharField(max_length=100)),
                ('flight_departure_time', models.CharField(max_length=100)),
                ('flight_destination_time', models.CharField(max_length=100)),
                ('flight_ticket_price', models.CharField(max_length=100)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.CharField(max_length=100)),
                ('passenger_gender', models.CharField(max_length=100)),
                ('passenger_phone', models.CharField(max_length=100)),
                ('passenger_email', models.CharField(max_length=100)),
                ('passenger_aadhar', models.CharField(max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
